apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: test-sliit
  name: test-sliit
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: test-sliit
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test-sliit
    spec:
      containers:
      - image: it19038292/docker_kubernets_cicd_test:9f8f6a7ac70f336bdd41ece3f0e7d4ddfde01665
        imagePullPolicy: Always
        name: docker-kubernets-cicd-test-2flz2
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        ports:
          - containerPort: 3000
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30